### ISSUE TITLE
cazy_extract.pl fails to get sequences

### ISSUE THREAD

**Issue by ckeuschn** [DallasThomas/SACCHARIS#3]
Hi Thomas

Sorry for not replying the last time, I was getting busy with another project which kept me from working on the cazy problem I had.
I cloned now all new scripts and got an account at NCBI but when I run cazy_extract.pl I still get error messages saying that some variables are undefined in the code. Like:
perl SACCHARIS/cazy_extract.pl -f GH42 -g characterized
Use of uninitialized value $esearch_result in pattern match (m//) at SACCHARIS/cazy_extract.pl line 461.
Use of uninitialized value $count in concatenation (.) or string at SACCHARIS/cazy_extract.pl line 465.
Use of uninitialized value $esearch_result in pattern match (m//) at SACCHARIS/cazy_extract.pl line 469.
Use of uninitialized value $esearch_result in pattern match (m//) at SACCHARIS/cazy_extract.pl line 472.
Use of uninitialized value $key in concatenation (.) or string at SACCHARIS/cazy_extract.pl line 480.
Use of uninitialized value $web in concatenation (.) or string at SACCHARIS/cazy_extract.pl line 480.
Use of uninitialized value $efetch_result in substitution (s///) at SACCHARIS/cazy_extract.pl line 485.
Use of uninitialized value $_ in split at SACCHARIS/cazy_extract.pl line 207.

I cannot figure out where the problem is, any help would be much appreciated!

Thanks
Christoph

**Comment by DallasThomas** [comment]
Was this with the most recent version of cazy_extract from Github?

This script just underwent a major revision so possible something happened here despite my testing.

I will take a look a bit later when I have access.

Dallas

From: ckeuschn
Sent: Wednesday, August 1, 2018 11:33 AM
To: DallasThomas/SACCHARIS
Reply To: DallasThomas/SACCHARIS
Cc: Subscribed
Subject: [DallasThomas/SACCHARIS] cazy_extract.pl fails to get sequences (#3)



Hi Thomas

Sorry for not replying the last time, I was getting busy with another project which kept me from working on the cazy problem I had.
I cloned now all new scripts and got an account at NCBI but when I run cazy_extract.pl I still get error messages saying that some variables are undefined in the code. Like:
perl SACCHARIS/cazy_extract.pl -f GH42 -g characterized
Use of uninitialized value $esearch_result in pattern match (m//) at SACCHARIS/cazy_extract.pl line 461.
Use of uninitialized value $count in concatenation (.) or string at SACCHARIS/cazy_extract.pl line 465.
Use of uninitialized value $esearch_result in pattern match (m//) at SACCHARIS/cazy_extract.pl line 469.
Use of uninitialized value $esearch_result in pattern match (m//) at SACCHARIS/cazy_extract.pl line 472.
Use of uninitialized value $key in concatenation (.) or string at SACCHARIS/cazy_extract.pl line 480.
Use of uninitialized value $web in concatenation (.) or string at SACCHARIS/cazy_extract.pl line 480.
Use of uninitialized value $efetch_result in substitution (s///) at SACCHARIS/cazy_extract.pl line 485.
Use of uninitialized value $_ in split at SACCHARIS/cazy_extract.pl line 207.

I cannot figure out where the problem is, any help would be much appreciated!

Thanks
Christoph

**Comment by ckeuschn** [comment]
Yes, I downloaded it today actually. Thanks for looking into that!

Christoph

**Comment by DallasThomas** [comment]
Hello Christoph,



I do apologize.  I am trying to remember, are you running this on OSX?  I tested cazy_extract.pl on my Debian machine with -f GH42 -g characterized and the script ran without any problems.



Can you let me know your OS and version.  Thanks.



Dallas

________________________________

**Comment by ckeuschn** [comment]
Hi,
I run the script on OS X El Capitan 10.11.6. I tried to run the script on Linux Ubuntu 14.04 LTS, but I got the same warnings after running cazy_extract.pl. In both cases I run it with perl installed via perlbrew (version 5.28.0). 
I attatched the sequence.count file I got after running cazy_extract.pl -f GH43 -g all. It also created an empty fasta-file.

Thanks
Ch

[sequence.count.txt](https://github.com/DallasThomas/SACCHARIS/files/2252497/sequence.count.txt)

**Comment by DallasThomas** [comment]
Hello,

Thanks for the information Christoph and I apologize for the delay.  Thank-you for being patient with me.  I was away all last week which hindered my response times.

I was wondering if you could give me some more information on your system?  RIght now preferably your Ubuntu box?  I will be back in tomorrow and am going to try and re-create your environment to see if I can reproduce your warnings and go from there.

Thanks
Dallas

**Comment by ckeuschn** [comment]
Hi
no worries I am glad that you are looking into this. As I mentioned I run Ubuntu 14.04 via Parallels Desktop 11 version 11.0.0. Let me know what you need further to track this problem.

ch

**Comment by DallasThomas** [comment]
Hello Christopher,

I am pretty sure I found the problem.  The error is due to bash not being able to find the get command.  On your ubuntu VM just install libwww-perl via

apt-get install libwww-perl

Everything should work now on the Ubuntu box.  For the mac there is a bit more going on here.  From what I have been able to track down currently is LWP is probing for https support via LWP::Protocol::https  at least on my mac currently running High Sierra

Installing this module from CPAN fails with the following

MIKEM/Net-SSLeay-1.85.tar.gz                 : make NO
 SULLR/IO-Socket-SSL-2.058.tar.gz         : make_test NO one dependency not OK (Net::SSLeay); additionally test harness failed
 OALDERS/LWP-Protocol-https-6.07.tar.gz

The Net-SSLeay module fails due to an inability to find openssl/err.h.  This currently points to either openssl is not installed - or if it is the path for openssl needs to be configured.  I ran out of time for tonight to test this much further.

I would suspect once openssl is installed correctly the Net-SSLeay will have no more issues and the install of the https module will finish.  The get function of LWP::Simple should then work correctly.

I hope this helps some.  I will see if I can finish the trail on my Mac to best help and will keep you posted.  

Dallas

**Comment by ckeuschn** [comment]
Hi Dallas

I could install LWP::Protocol::https on my mac without error messages and after that cazy_extract.pl worked and produced a fasta and .count file. I will test later if it is also working on the Ubuntu box. 
Thanks for your quick help, this program is really helpful for my next research tasks! You can close this issue as solved ;)

Cheers
Christoph

**Comment by DallasThomas** [comment]
Glad to hear things are working now.  Have a great day.
